// Common English words dictionary (simplified for demo)
// In production, you'd use a comprehensive dictionary API
const VALID_WORDS = new Set([
  "cat", "dog", "bat", "rat", "hat", "mat", "sat", "fat", "pat",
  "cats", "dogs", "bats", "rats", "hats", "mats",
  "the", "and", "for", "are", "but", "not", "you", "all", "can", "her", "was", "one", "our", "out", "day",
  "go", "me", "he", "we", "be", "to", "do", "no", "so", "up", "at", "on", "in", "is", "it", "of", "or", "as",
  "car", "far", "war", "tar", "bar", "jar", "star", "scar", "char",
  "cars", "bars", "jars", "wars", "stars", "scars",
  "run", "sun", "fun", "gun", "bun", "nun", "runs", "guns", "buns",
  "red", "bed", "fed", "led", "wed", "reds", "beds",
  "set", "get", "met", "net", "pet", "vet", "wet", "bet", "jet", "let", "yet",
  "sets", "gets", "nets", "pets", "vets", "bets", "jets",
  "big", "dig", "fig", "gig", "jig", "pig", "rig", "wig",
  "hot", "got", "lot", "not", "pot", "rot", "tot", "dot", "cot", "jot",
  "bag", "gag", "hag", "jag", "lag", "nag", "rag", "sag", "tag", "wag", "bags", "rags", "tags",
  "boy", "coy", "joy", "soy", "toy", "boys", "joys", "toys",
  "box", "fox", "pox", "boxes",
  "bug", "dug", "hug", "jug", "mug", "pug", "rug", "tug", "bugs", "hugs", "jugs", "mugs", "pugs", "rugs",
  "cut", "gut", "hut", "jut", "nut", "rut", "cuts", "guts", "huts", "nuts",
  "fit", "hit", "kit", "lit", "pit", "sit", "wit", "bits", "fits", "hits", "kits", "pits",
  "gap", "lap", "map", "nap", "rap", "sap", "tap", "zap", "gaps", "laps", "maps", "naps", "raps", "taps",
  "ham", "jam", "ram", "yam", "dam", "hams", "jams", "rams",
  "hen", "men", "pen", "ten", "yen", "den", "hens", "pens",
  "ice", "ace", "rice", "dice", "mice", "nice", "vice", "lice", "price", "slice", "twice", "spice",
  "job", "mob", "rob", "sob", "jobs", "mobs",
  "kid", "lid", "rid", "kids", "lids",
  "lab", "tab", "cab", "dab", "gab", "jab", "nab", "labs", "tabs", "cabs",
  "mad", "dad", "bad", "had", "lad", "pad", "sad", "lads", "pads",
  "man", "ban", "can", "fan", "pan", "ran", "tan", "van", "men", "bans", "cans", "fans", "pans", "vans",
  "mix", "fix", "six", "mixed",
  "old", "cold", "gold", "hold", "sold", "told", "bold", "fold", "mold",
  "ape", "apes", "cape", "gape", "tape", "capes", "tapes",
  "age", "cage", "page", "rage", "sage", "wage", "ages", "cages", "pages", "rages", "wages",
  "art", "cart", "dart", "part", "tart", "arts", "carts", "darts", "parts",
  "ask", "task", "mask", "asks", "tasks", "masks",
  "ate", "date", "fate", "gate", "hate", "late", "mate", "rate", "dates", "gates", "hates", "mates", "rates",
  "back", "pack", "rack", "sack", "tack", "black", "crack", "track", "backs", "packs", "racks", "sacks",
  "ball", "call", "fall", "hall", "mall", "tall", "wall", "balls", "calls", "falls", "halls", "malls", "walls",
  "band", "hand", "land", "sand", "bands", "hands", "lands",
  "bank", "rank", "tank", "blank", "banks", "ranks", "tanks",
  "bare", "care", "dare", "fare", "rare", "ware", "cares", "dares", "fares",
  "base", "case", "vase", "bases", "cases", "vases",
  "bean", "dean", "lean", "mean", "beans", "leans", "means",
  "bear", "dear", "fear", "gear", "hear", "near", "pear", "rear", "tear", "wear", "year", "bears", "gears", "pears", "tears", "years",
  "beat", "feat", "heat", "meat", "neat", "peat", "seat", "beats", "heats", "meats", "seats",
  "bell", "cell", "fell", "sell", "tell", "well", "yell", "bells", "cells", "sells", "wells",
  "belt", "felt", "melt", "belts",
  "bend", "lend", "mend", "send", "tend", "bends", "lends", "mends", "sends",
  "bent", "dent", "rent", "sent", "tent", "vent", "went", "dents", "rents", "tents", "vents",
  "best", "nest", "pest", "rest", "test", "vest", "west", "nests", "pests", "rests", "tests", "vests",
  "bike", "hike", "like", "mike", "bikes", "hikes", "likes",
  "bill", "fill", "hill", "kill", "mill", "pill", "will", "bills", "fills", "hills", "kills", "mills", "pills",
  "bird", "birds",
  "bite", "kite", "site", "bites", "kites", "sites",
  "blow", "flow", "glow", "slow", "blows", "flows", "glows",
  "blue", "clue", "glue", "true", "blues", "clues",
  "boat", "coat", "goat", "moat", "boats", "coats", "goats",
  "body", "bodies",
  "boil", "coil", "foil", "soil", "boils", "coils", "soils",
  "bold", "cold", "fold", "gold", "hold", "mold", "sold", "told",
  "bone", "cone", "done", "gone", "lone", "none", "tone", "zone", "bones", "cones", "tones", "zones",
  "book", "cook", "hook", "look", "took", "books", "cooks", "hooks", "looks",
  "boot", "foot", "hoot", "loot", "root", "soot", "boots", "roots",
  "bore", "core", "fore", "gore", "more", "pore", "sore", "tore", "wore", "bores", "cores", "pores", "sores",
  "born", "corn", "horn", "morn", "torn", "worn",
  "boss", "loss", "moss", "toss",
  "both",
  "bowl", "fowl", "howl", "jowl", "bowls",
  "brace", "grace", "place", "space", "trace", "braces", "graces", "places", "spaces", "traces",
  "brain", "drain", "grain", "train", "brains", "drains", "grains", "trains",
  "brake", "drake", "flake", "shake", "snake", "stake", "brakes", "flakes", "shakes", "snakes", "stakes",
  "brand", "grand", "stand", "brands", "stands",
  "brass",
  "brave", "crave", "grave", "shave", "slave", "braves", "graves", "shaves", "slaves",
  "bread", "dread", "tread", "breads",
  "break", "steak", "breaks", "steaks",
  "breed", "greed", "speed", "breeds",
  "brick", "click", "quick", "slick", "stick", "thick", "trick", "bricks", "clicks", "sticks", "tricks",
  "bride", "glide", "pride", "slide", "brides", "glides", "slides",
  "brief", "chief", "grief", "thief", "briefs", "chiefs", "thieves",
  "bring", "cling", "fling", "sling", "sting", "swing", "thing", "brings", "clings", "flings", "slings", "swings", "things",
  "brink", "drink", "think", "drinks", "thinks",
  "broad",
  "broke", "choke", "smoke", "spoke", "stroke", "chokes", "smokes", "strokes",
  "broom", "groom", "brooms", "grooms",
  "broth",
  "brown", "clown", "crown", "drown", "frown", "grown", "browns", "clowns", "crowns", "frowns",
  "brush",
  "build", "guild", "builds", "guilds",
]);

export const validateWord = (word: string): boolean => {
  const lowerWord = word.toLowerCase();
  
  // Check length (2-9 letters)
  if (lowerWord.length < 2 || lowerWord.length > 9) {
    return false;
  }
  
  // Check if it's a valid word
  return VALID_WORDS.has(lowerWord);
};
